require "simple_deploy/aws/cloud_formation"
require "simple_deploy/aws/cloud_formation/error"
require "simple_deploy/aws/ec2"
require "simple_deploy/aws/simpledb"
require "simple_deploy/aws/auto_scaling_groups"
