#!/bin/bash

# Source RVM profile and set ruby / gemset
. /etc/profile

# Exit with error if any command returns non zero
set -e

# Bundle gems
rvm use "1.9.3-p125@simple_deploy" --create
bundle

# Run spec tests
rspec spec
