#!/bin/bash

# Source RVM profile and set ruby / gemset
. /etc/profile
rvm use "1.9.3-p125@simple_deploy" --create

# Bundle gems
bundle

# Create blank deployment config
touch $HOME/.simple_deploy.yml

# Run spec tests
rspec spec
